### ISSUE TITLE
Custom unit specific icon stops working after rejoining the group

### ISSUE THREAD

**Issue by veteran29** [diwako/diwako_dui#104]
1. Add custom icon to unit
2. Leave the group
3. Join the group
4. Icon does not work

https://streamable.com/syptu

**Comment by diwako** [comment]
Thanks for the report, the video explains what is going on. Right now only 2 icons have priority to the custom icon, that is squad leader and buddy icon. I actually forgot to document this, that those 2 cases are the exception.

In your case when you rejoined the group you became immediately the squad leader, so that icon was prioritized.

**Comment by veteran29** [comment]
When I joined the AI I was a leader again and the icon was added to AI guy. He was not a buddy too.

**Comment by veteran29** [comment]
Seems to be fixed by DEV branch too.
