### ISSUE TITLE
Feature - DUI nametags

### ISSUE THREAD

**Issue by nk3nny** [diwako/diwako_dui#136]
Hi Diwako, 
It would be great to get a simple name tag system married into the DUI infrastructure. 

**Configurable for:** 
1. Show nametag based on _Aimed position_ or _Looked position_ 
2. Show information such as:  group, rank, is speaking (voice or radio) and name. 
3. Colourised, fonts, distance of names, and so on set by DUI default settings. 

**Ideally the nametag is drawn center screen**. In ACE3 it is drawn above the head of unit. The problem is that the text is linked to the heads movement,  which when combined with movement makes it difficult to read. 

**Making it configurable for _aimed position_ or _looked position_ would be a nice touch**.  The latter option being preferred. Looked position is easier for TrackIR users and means that you do not need to aim your weapon at a potential ally to check names. 

Thank you for reading
nkenny

**Comment by nk3nny** [comment]
What a clever idea. I support this! 

-k 

/s

**Comment by Drofseh** [comment]
I don't mind this existing, but it was one of the things I hated most about STHud, so please make it optional.

**Comment by Fusselwurm** [comment]
Why should this be implemented here instead of in ACE where the basic feature  already exists?

**Comment by diwako** [comment]
> Why should this be implemented here instead of in ACE where the basic feature already exists?

There are communities that prefer STUI style nametags over aces.

That said. I am currently busy IRL however there already was some internal talk how to implement this.

**Comment by jokoho48** [comment]
> Why should this be implemented here instead of in ACE where the basic feature already exists?

the ACE nametags are fairly big on-screen and also blocking. the simple style STUI nametags are small and can be easier moved to parts of the screen where they are not blocking the view directly

**Comment by Quailsnap** [comment]
I've always thought STUI nametags were more of a nuisance because the screen real-estate they took up is the most important part of the screen (the center) and they were very garish compared to ACE3's somewhat more transparent tags.

A few years back I made a rudimentary nametags system that a few of my units (Folk ARPs, coalition, and TMTM) have been using ever since. It dealt with a few complaints I had, and was inspired by a few things I liked, from ACE's nametag system, from STUI, and from F3's nametag system. I would be fine implementing this into DUI if anyone is interested.

Repo: https://github.com/Quailsnap/WHA-Nametags
See: https://www.twitch.tv/videos/739343427?t=04h00m54s
Note that the tags can be configured by clients to only show for the unit closest to the cursor, or to not show role and/or group, etc etc. The "defaults" can also be changed.

Thought process for the tags I made:
- Soldiers in the same unit will know each other by appearance almost always
- If you can see someone you know well enough to recognize their face, their role, name, and group will be displayed on their chest
- Their chest is the least valuable "screen real estate" I can think of -- no enemies will ever be lurking there
- The chest also usually has good contrast compared to the variable sky/wall/interior/snow/grass that may be above their head or in the center of your screen

How this is different from ACE3:
- Names will show at any range as long as you can zoom in far enough and look directly at the target. In a practical sense, by default they show to about double the distance of ACE3
- group and role is displayed. role draws from unit configs, which can be inaccurate, but a variable can be set (and I can, later, make this more automatic) to make the 'role' say anything
- IFF is a lot easier with this script. Too easy? Maybe
- The increased contrast compared ACE3 (at least with default settings) can make them a bit garish
- There is no system (yet) for displaying ranks, and the system for displaying whether someone is "Speaking" is very rudimentary
- vehicle passenger tags work much more often, now
- more robust support for vehicles in general. as QoL it also displays how many passenger slots a vehicle has

Things that could be improved:
- reliance on cursorTarget occasionally makes friendlies show through walls if you look directly at them
- tons of little features I want to introduce, recorded in the repo issue tracker

**Comment by jokoho48** [comment]
@Quailsnap I already talked to diwako and implemented the nametags into DUI. nkenny, diwako and I are already testing it internally in a group we play at. the PR will be around to Hacktoberfest. so you can look over it than I gues

**Comment by Quailsnap** [comment]
Looking forward to seeing them! If you can, an interesting feature might be to allow tags to be identified at long range if someone can zoom in enough (ie: using binoculars to identify people).

https://cbateam.github.io/CBA_A3/docs/files/common/fnc_getFov-sqf.html

**Comment by diwako** [comment]
Feature preview available on dev branch
https://steamcommunity.com/sharedfiles/filedetails/?id=1617125729
