### ISSUE TITLE
Feature - Suggestion: Omnipresent units

### ISSUE THREAD

**Issue by nk3nny** [diwako/diwako_dui#33]
Suggestion:  Add the ability to mark certain units to always appear in all DUI radars. 

This is particularly useful for Officers or platoon sergeants.  Roles which generally operate near but external to squads. 

I suggest the pink or purple colour be ressurected. :)

**Comment by diwako** [comment]
I get the use case for this. But since this is a clientside mod, I am wondering how to implement something like this. Potentially not everyone (including server) is running this mod, so a function is already out of the question.
Then only a global variable is left, but then, do you want that to be synced, set it only on per unit basis? So should every client have this variable set or not? Ultimately the mission maker needs to decide.
I also take it only units should be tracked as there is no support for showing vehicles so far.

**Comment by diwako** [comment]
As an idea, I thought maybe vehicles could be tracked as well, so I added support for this. Here is the idea of it with very """nice""" color. Vehicle icons are twice the size of unit icons
![image](https://user-images.githubusercontent.com/8259498/52533630-c9490300-2d36-11e9-9d47-78d860ba2c6f.png)

**Comment by nk3nny** [comment]
Vehicles may be a cool experiment.  I think a global variable, essentially an array where the relevant unit name added is simple enough to use.  No extra interface is necessary.

**Comment by diwako** [comment]
Right now the implementation is it checks for an array which is named `diwako_dui_special_track` in misionNamespace. Adds all objects to the compass tracker if these are based on `CAManBase`, `Air` or `LandVehicle`.

For vehicles it grabs the map icon.

**Comment by Drofseh** [comment]
@diwako I would love to be able to add vehicle tracking on a per squad basis.
Assign Vehicle A to Squad A, Vehicle B to Squad B, etc, so only your the vehicle assigned to your squad would appear in your hud.

This would make it much easier for each squad to find their own vehicle when mounting up.

Maybe an ace interaction on the vehicle as well to reassign it?
So that if a squad changes vehicle mid-mission they could switch which vehicle is being tracked in their hud.

**Comment by diwako** [comment]
I don't really intent that SQLs or any players mid mission can add things to the array. I'd prefer it to be a advanced mission maker thing. Hence just a variable in missionNamespace which a mission maker is free to play around with.
That means starting assigned vehicles could be done on mission set up, switching vehicles mid mission could be done via some mission addaction/ace interaction. I am pretty sure several people who want an "out of squad" tracking thing will use it in multitude of ways.

**Comment by diwako** [comment]
Commit a1f1e22a953dfc92c354a6a4e7bc919ef119974a has all changes discussed here.

**Comment by Drofseh** [comment]
Sounds good. Could you give an example of adding a unit to the special tracking mid-mission?
Just `diwako_dui_group = diwako_dui_group + [UnitVar];` ?

**Comment by diwako** [comment]
Sure thing.
It uses the variable named `diwako_dui_special_track`. You should not use the var `diwako_dui_group` as it will be constantly overwritten.

`diwako_dui_special_track` is nil by default. so you start with defining it, let's say in initPlayerLocal.sqf.
```sqf
diwako_dui_special_track = [alpha_vic];
```

To add to it mid mission, you can either `pushBack` a new vehicle or just redefine the whole array in `diwako_dui_special_track`. Changes to the array are automatically picked up.

**Comment by Drofseh** [comment]
Cool, thanks.
I think it might be worth writing things like that in the wiki here on github.

**Comment by diwako** [comment]
Depends what the mission maker intents, they could just publicVar it if they only have like a VIP, or have them local only for stuff like "squad vehicles"

**Comment by diwako** [comment]
Closing this now, but leaving comments open as the changes are already commited

**Comment by Drofseh** [comment]
Any chance we could change the default colour for this?
Or have the colour as a setting. I'd just like it to be white for me.

**Comment by diwako** [comment]
I kind of want the color to be tied to the color schemes, so they are all consistent with future™ features. I can understand that the current color is probably not that desirable for many people.

Would you mind opening up a new issue so I can track that for v1.4.0?

**Comment by Drofseh** [comment]
Sure
