### ISSUE TITLE
Feature - Predefined icon per unit

### ISSUE THREAD

**Issue by Lifetap** [diwako/diwako_dui#96]
Is it possible to have the get_icon function look for a variable on the unit that could be used to store a default icon.
This would prevent the case where a different icon is required than automatically assigned by DUI.  For example, a TL with the ACE medic property enabled is currently given a medic icon, not a team lead icon.

**Comment by diwako** [comment]
I am thinking of implementing it in a way so that the Buddy and SQL icons have still higher priority, but it will overwrite every other icon. The namelist icons for when in a vehicle will not change however, meaning passengers, gunners, ffv seats, and drivers icon will take priority to indicate the unit is in a vehicle.

**Comment by diwako** [comment]
![image](https://user-images.githubusercontent.com/8259498/57541275-e6e63280-734e-11e9-98d5-15d49ce2fddf.png)
First implementation seems to work just fine. I pushed this to the DEV workshop item for preview

You can add the icon to a unit like this
```sqf
_unit setVariable ["diwako_dui_radar_customIcon", "yes.paa", true];
```

https://steamcommunity.com/sharedfiles/filedetails/?id=1617125729
